kind: Deployment
apiVersion: apps/v1
metadata:
  name: webapp
  namespace: local
  generation: 4
  labels:
    app: webapp
    layer: backend
  annotations:
    deployment.kubernetes.io/revision: '2'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: 'myrepo/spring-docker-webapp'
          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 2
            periodSeconds: 5  
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 2
            periodSeconds: 5                             
          resources:
            requests:
              memory: "32Mi"
              cpu: "200m"
            limits:
              memory: "128Mi"
              cpu: "500m"  
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Never
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 4
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2020-04-25T19:41:13Z'
      lastTransitionTime: '2020-04-25T19:39:07Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "webapp-7bbff9d46f" has successfully progressed.
    - type: Available
      status: 'True'
      lastUpdateTime: '2020-04-25T19:43:46Z'
      lastTransitionTime: '2020-04-25T19:43:46Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
