
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: consul-server
  namespace: consul
  labels:
    app: consul
  annotations:
    deployment.kubernetes.io/revision: '2'
spec:
  replicas: 3
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
        - name: consul
          image: 'consul:latest'
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          ports:
            - containerPort: 8500
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8500
            initialDelaySeconds: 30
            timeoutSeconds: 2
            periodSeconds: 5  
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8500
            initialDelaySeconds: 30
            timeoutSeconds: 2
            periodSeconds: 5                             
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "500Mi"
              cpu: "500m"  
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 300
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600


---
apiVersion: v1
kind: Service
metadata:
  name: consul
  namespace: consul
spec:
  selector:
    app: consul
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8500
  type: ClusterIP
